### ISSUE TITLE
status code is not defined error.

### ISSUE THREAD

**Issue by chenghung** [koshuang/ricloud-js#14]
```
2017-05-03T08:28:17.164Z - error: uncaughtException: statusCode is not defined
2017-05-03T08:28:17.165Z - error: ReferenceError: statusCode is not defined
    at Request.callback [as _callback] (/opt/www/kid-guard-backend/shared/node_modules/ricloud/dist/ricloud.js:109:60)
    at Request.self.callback (/opt/www/kid-guard-backend/shared/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/www/kid-guard-backend/shared/node_modules/request/request.js:1035:10)
```

```
  function callback(error, response, body) {
    body = body || '{}';
    response.body = body;
    # error is threw on below line. 
    debug(`login result: status code: ${response.statusCode}, data:`, response.body);
```

**Comment by chenghung** [comment]
request module may not callback a response if there is non http API error.
